import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createApp } from '../apps/server/app.js';
import { createPages } from '../packages/contracts/domain.js';
import { copyPrompt } from '../packages/contracts/copy.js';
import { Tasks } from '../apps/server/tasks.js';
import { qualityAppliesToCurrentPage } from '../apps/server/content-production.js';

const headers = { host: '127.0.0.1:4380', origin: 'http://127.0.0.1:4380' };

test('V10 retains existing SKU identity and links a selected direction to a real production batch', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'commerce-v10-'));
  const { app, store } = await createApp(directory);
  t.after(() => app.close());
  assert.equal(Number(store.db.prepare('PRAGMA user_version').get()!.user_version), 16);
  assert.ok(readdirSync(directory).some(name => name.startsWith('before-content-production-v10-')));
  const sku = store.createProduct({ name: '测试沐浴露', brand: '测试品牌', variant: '', specification: '500ml', audience: '', origin: '', notes: '', claims: [{ id: randomUUID(), label: '保湿', text: '滋润肤感', source: '业务资料', status: 'provided' }] });
  const category = store.db.prepare('SELECT id FROM categories ORDER BY rowid LIMIT 1').get()!;
  const post = (url: string, payload: unknown, idempotencyKey?: string) => app.inject({ method: 'POST', url, headers: idempotencyKey ? { ...headers, 'Idempotency-Key': idempotencyKey } : headers, payload: payload as Record<string, unknown> });
  const projectResponse = await post(`/api/products/${sku.id}/existing-project`, { projectName: '测试商品运营', categoryId: String(category.id), confirmExistingProduct: true });
  assert.equal(projectResponse.statusCode, 201);
  const projectId = projectResponse.json().projectId as string;
  assert.equal(store.product(sku.id).id, sku.id);
  assert.equal(store.product(sku.id).spuId, null);
  assert.equal((await post(`/api/products/${sku.id}/existing-project`, { projectName: '重复项目', categoryId: String(category.id), confirmExistingProduct: true })).statusCode, 409);
  const unconfirmed = await post(`/api/product-projects/${projectId}/content-directions`, { skuId: sku.id, title: '保湿', objective: '突出保湿', factRefs: [`claim:${sku.claims[0]!.id}`], marketRefs: [] });
  assert.equal(unconfirmed.statusCode, 409);
  const directionResponse = await post(`/api/product-projects/${projectId}/content-directions`, { skuId: sku.id, title: '品牌识别', objective: '清楚介绍现有商品', factRefs: ['product.name','product.specification'], marketRefs: [] });
  assert.equal(directionResponse.statusCode, 201);
  const directionId = directionResponse.json().id as string;
  assert.equal((await post('/api/content-production-batches', { directionId, kitId: randomUUID(), pageIds: [randomUUID()] }, randomUUID())).statusCode, 409);
  assert.equal((await post(`/api/content-directions/${directionId}/select`, {})).statusCode, 200);
  const overviewAssetId = randomUUID();
  store.db.prepare('INSERT INTO assets VALUES (?,?,?,?,?,?,?,?,?,?)').run(overviewAssetId, sku.id, '测试素材', 'image/png', 1080, 1080, 'upload', 'overview-test.png', 'testhash', new Date().toISOString());
  const kit = store.createKit(sku.id, { name: '淘宝商品图', productVersion: sku.version, pages: createPages(sku, 12, overviewAssetId) });
  const overview = await app.inject({ method: 'GET', url: '/api/overview-work', headers });
  const projectWork = overview.json().attention.find((item: { target: { projectId?: string }; kind: string }) => item.kind === 'project' && item.target.projectId === projectId);
  assert.notEqual(projectWork?.target.projectAction, 'sku', 'attached independent SKU must not be reported as missing');
  const contentWork = overview.json().attention.find((item: { target: { kitId?: string } }) => item.target.kitId === kit.id);
  assert.equal(contentWork?.target.projectId, projectId, 'content todo must retain independent SKU project context');
  const directedPrompt = copyPrompt(sku, kit.pages[0]!, [], undefined, undefined, { title: '品牌展示', objective: '突出真实商品外观' });
  assert.deepEqual(JSON.parse(directedPrompt[1]!.content).content_direction, { title: '品牌展示', objective: '突出真实商品外观' });
  assert.equal(JSON.parse(copyPrompt(sku, kit.pages[0]!, [])[1]!.content).content_direction, null);
  const batchPayload = { directionId, kitId: kit.id, pageIds: kit.pages.map(page => page.id) };
  const batchKey = randomUUID();
  const batchResponse = await post('/api/content-production-batches', batchPayload, batchKey);
  assert.equal(batchResponse.statusCode, 201);
  const batchId = batchResponse.json().id as string;
  assert.equal((await post('/api/content-production-batches', batchPayload, batchKey)).json().id, batchId);
  assert.equal(store.db.prepare('SELECT count(*) AS count FROM content_production_batches').get()!.count, 1);
  const batch = await app.inject({ method: 'GET', url: `/api/content-production-batches/${batchId}`, headers });
  assert.equal(batch.statusCode, 200);
  assert.deepEqual(batch.json().metrics, { planned: 17, generated: 0, copyGenerated: 0, visualGenerated: 0, ruleEvaluated: 0, firstRulePassed: 0, firstRulePassRate: null, firstHumanReviewed: 0, firstHumanApproved: 0, firstHumanPassRate: null, humanRejected: 0, humanDecisionCount: 0, returnRate: null, retries: 0, attemptedPageCount: 0, averageRetries: null });
  const quality = await post(`/api/content-production-batches/${batchId}/quality/${kit.pages[0]!.id}`, {});
  assert.equal(quality.statusCode, 201);
  assert.equal(quality.json().ruleStatus, 'FAIL');
  assert.equal((await post(`/api/content-quality-results/${quality.json().id}/decision`, { decision: 'APPROVE' })).statusCode, 409);
  assert.equal((await post(`/api/content-quality-results/${quality.json().id}/decision`, { decision: 'REJECT' })).statusCode, 200);
  assert.equal(store.kit(kit.id).version, 2);
  const assetId = randomUUID();
  store.db.prepare('INSERT INTO assets VALUES (?,?,?,?,?,?,?,?,?,?)').run(assetId, sku.id, '测试素材', 'image/png', 1080, 1080, 'upload', 'test.png', 'testhash', new Date().toISOString());
  const current = store.kit(kit.id);
  store.saveKit(kit.id, current.version, { name: current.name, productVersion: current.productVersion, pages: current.pages.map(page => page.id === kit.pages[0]!.id ? { ...page, templateId: 'D12', headline: '测试品牌沐浴露', subtitle: '500ml', assetId, copyStatus: 'confirmed', sourceFactIds: ['product.name'] } : page) });
  const passing = await post(`/api/content-production-batches/${batchId}/quality/${kit.pages[0]!.id}`, {});
  assert.equal(passing.statusCode, 201);
  assert.equal(passing.json().ruleStatus, 'PASS');
  assert.equal(passing.json().aiStatus, 'FAILED');
  assert.equal((await post(`/api/content-quality-results/${passing.json().id}/decision`, { decision: 'APPROVE' })).statusCode, 200);
  assert.equal(store.kit(kit.id).pages[0]!.reviewed, true);
  assert.equal((await post(`/api/content-quality-results/${passing.json().id}/decision`, { decision: 'APPROVE' })).statusCode, 409);
  const approvedResult = store.db.prepare('SELECT * FROM content_quality_results WHERE id=?').get(passing.json().id)!;
  assert.equal(qualityAppliesToCurrentPage(store, approvedResult), true, 'approval revision must not hide its own quality decision');
  const beforeChecklist = store.kit(kit.id);
  store.saveKit(kit.id, beforeChecklist.version, { name: beforeChecklist.name, productVersion: beforeChecklist.productVersion, pages: beforeChecklist.pages.map(page => page.id === kit.pages[0]!.id ? { ...page, visualReviewChecks: ['PRODUCT_IDENTITY', 'COPY_ACCURACY'] } : page) });
  assert.equal(qualityAppliesToCurrentPage(store, approvedResult), true, 'human checklist records must not invalidate the content they review');
  const beforeOtherPage = store.kit(kit.id);
  store.saveKit(kit.id, beforeOtherPage.version, { name: beforeOtherPage.name, productVersion: beforeOtherPage.productVersion, pages: beforeOtherPage.pages.map((page,index) => index === 1 ? { ...page, headline: '另一页修改' } : page) });
  assert.equal(qualityAppliesToCurrentPage(store, approvedResult), true, 'another page must not erase this page approval');
  const beforeOwnPage = store.kit(kit.id);
  store.saveKit(kit.id, beforeOwnPage.version, { name: beforeOwnPage.name, productVersion: beforeOwnPage.productVersion, pages: beforeOwnPage.pages.map(page => page.id === kit.pages[0]!.id ? { ...page, subtitle: '重新核对规格' } : page) });
  assert.equal(qualityAppliesToCurrentPage(store, approvedResult), false, 'changed page must not inherit old approval');
  const beforeFailedDecision = store.kit(kit.id);
  assert.throws(() => store.saveKit(kit.id, beforeFailedDecision.version, { name: beforeFailedDecision.name, productVersion: beforeFailedDecision.productVersion, pages: beforeFailedDecision.pages.map(page => page.id === kit.pages[0]!.id ? { ...page, reviewed: true } : page) }, () => { throw new Error('decision write failed'); }), /decision write failed/);
  assert.equal(store.kit(kit.id).version, beforeFailedDecision.version, 'failed decision must roll back the kit revision');
  assert.equal(store.kit(kit.id).pages[0]!.reviewed, beforeFailedDecision.pages[0]!.reviewed);
  const prior = Object.fromEntries(['COMMERCE_COPY_ENABLED', 'COMMERCE_BAILIAN_WORKSPACE_ID', 'DASHSCOPE_API_KEY'].map(name => [name, process.env[name]]));
  process.env.COMMERCE_COPY_ENABLED = '1';
  process.env.COMMERCE_BAILIAN_WORKSPACE_ID = 'test-workspace';
  process.env.DASHSCOPE_API_KEY = 'test-only-not-a-real-key';
  try {
    const pageWithoutClaims = kit.pages.find(page => page.claimIds.length === 0)!;
    const job = new Tasks(store).submit(kit.id, { kitVersion: store.kit(kit.id).version, operation: 'copy', pageIds: [pageWithoutClaims.id], productionBatchId: batchId }, randomUUID());
    const row = store.db.prepare('SELECT input_snapshot FROM jobs WHERE id=?').get(job.id)!;
    const snapshot = JSON.parse(String(row.input_snapshot));
    assert.deepEqual(JSON.parse(snapshot.copyPrompts[pageWithoutClaims.id][1].content).content_direction, { title: '品牌识别', objective: '清楚介绍现有商品' });
  } finally {
    for (const [name, value] of Object.entries(prior)) if (value === undefined) delete process.env[name]; else process.env[name] = value;
  }
  assert.equal(store.db.prepare('PRAGMA foreign_key_check').all().length, 0);
});

test('SPU facts changed after quality evaluation require a new quality check', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'commerce-quality-facts-'));
  const { app, store } = await createApp(directory);
  t.after(() => app.close());
  const category = store.db.prepare("SELECT id FROM categories WHERE code='shampoo'").get();
  assert.ok(category);
  const project = await app.inject({ method: 'POST', url: '/api/product-projects', headers, payload: { categoryId: String(category.id), projectType: 'NEW_PRODUCT', name: '香调质检测试', objective: '', positioning: '', constraints: [], notes: '' } });
  assert.equal(project.statusCode, 201);
  const spu = await app.inject({ method: 'POST', url: `/api/product-projects/${project.json().project.id}/spus`, headers, payload: { categoryId: String(category.id), brand: '测试品牌', name: '香氛洗发水', positioning: '', targetAudience: '', coreClaims: ['香氛'], dynamicAttributes: { fragrance: '花香' }, status: 'ACTIVE' } });
  assert.equal(spu.statusCode, 201);
  const sku = store.createProduct({ name: '香氛洗发水', brand: '测试品牌', variant: '', specification: '500ml', audience: '', origin: '', notes: '', claims: [] }, spu.json().id);
  const kit = store.createKit(sku.id, { name: '香调套图', productVersion: sku.version, pages: createPages(sku) });
  const result = { kit_id: kit.id, kit_version: kit.version, page_id: kit.pages[0]!.id, human_decision: null, created_at: '2099-01-01T00:00:00.000Z' };
  assert.equal(qualityAppliesToCurrentPage(store, result), true);
  store.db.prepare('UPDATE spus SET updated_at=? WHERE id=?').run('2099-01-02T00:00:00.000Z', spu.json().id);
  assert.equal(qualityAppliesToCurrentPage(store, result), false);
});
