import test from 'node:test';
import assert from 'node:assert/strict';
import { copyFileSync, mkdtempSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { Store } from '../apps/server/store.js';
import { createApp } from '../apps/server/app.js';
import type { Category, ProjectDetail } from '../packages/contracts/business.js';
import type { MarketResearchJob } from '../packages/contracts/market-research.js';
import { columns, csvText } from '../packages/contracts/market.js';
import { createMarketResearchOpportunities } from '../apps/server/market-opportunity.js';
import { processMarketResearchJob } from '../apps/server/market-research.js';
import { AppError } from '../apps/server/store.js';
import type { OpportunityPreview, ProductOpportunity } from '../packages/contracts/market-opportunity.js';

const headers = { host: '127.0.0.1:4380', origin: 'http://127.0.0.1:4380' };

test('V8 migration backs up V7, retains global research and historical relationships', () => {
  const seedDir = mkdtempSync(join(tmpdir(), 'project-research-seed-'));
  const seed = new Store(seedDir);
  seed.close();
  const v7Backup = readdirSync(seedDir).find(name => name.startsWith('before-project-research-v8-'))!;
  const directory = mkdtempSync(join(tmpdir(), 'project-research-v8-'));
  copyFileSync(join(seedDir, v7Backup), join(directory, 'workbench.sqlite'));
  const db = new DatabaseSync(join(directory, 'workbench.sqlite'));
  db.exec('PRAGMA foreign_keys=ON');
  const time = new Date().toISOString(), jobId = randomUUID(), projectId = randomUUID();
  const categoryId = String(db.prepare("SELECT id FROM categories WHERE code='shampoo'").get()!.id);
  db.prepare('INSERT INTO product_projects VALUES (?,?,?,?,?,?,?,?)').run(projectId, categoryId, '历史项目', 'DRAFT', '{}', '{}', time, time);
  db.prepare('INSERT INTO market_research_jobs (id,source_platform,collection_profile,target_count,max_pages,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').run(jobId, 'jd', 'shampoo', 50, 10, 'COMPLETED', time, time);
  db.close();
  const migrated = new Store(directory);
  assert.equal(Number(migrated.db.prepare('PRAGMA user_version').get()!.user_version), 16);
  assert.equal(migrated.db.prepare('SELECT initiating_project_id FROM market_research_jobs WHERE id=?').get(jobId)!.initiating_project_id, null);
  assert.equal(Number(migrated.db.prepare('SELECT count(*) count FROM market_research_jobs').get()!.count), 1);
  assert.equal(Number(migrated.db.prepare('SELECT count(*) count FROM product_projects').get()!.count), 1);
  assert.ok(migrated.db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='market_research_project_history'").get());
  assert.deepEqual(migrated.db.prepare('PRAGMA foreign_key_check').all(), []);
  const saved = readdirSync(directory).find(name => name.startsWith('before-project-research-v8-'))!;
  const backup = new DatabaseSync(join(directory, saved));
  assert.equal(Number(backup.prepare('PRAGMA user_version').get()!.user_version), 7);
  assert.equal(Number(backup.prepare('SELECT count(*) count FROM market_research_jobs').get()!.count), 1);
  backup.close(); migrated.close();
});

test('V8 migration rolls back the column when its index conflicts', () => {
  const seedDir = mkdtempSync(join(tmpdir(), 'project-research-conflict-seed-'));
  const seed = new Store(seedDir); seed.close();
  const v7Backup = readdirSync(seedDir).find(name => name.startsWith('before-project-research-v8-'))!;
  const directory = mkdtempSync(join(tmpdir(), 'project-research-conflict-'));
  copyFileSync(join(seedDir, v7Backup), join(directory, 'workbench.sqlite'));
  const db = new DatabaseSync(join(directory, 'workbench.sqlite'));
  db.exec('CREATE INDEX market_research_project_history ON market_research_jobs(created_at)');
  db.close();
  assert.throws(() => new Store(directory));
  const after = new DatabaseSync(join(directory, 'workbench.sqlite'));
  assert.equal(Number(after.prepare('PRAGMA user_version').get()!.user_version), 7);
  assert.equal(after.prepare('PRAGMA table_info(market_research_jobs)').all().some(row => row.name === 'initiating_project_id'), false);
  assert.deepEqual(after.prepare('PRAGMA foreign_key_check').all(), []);
  after.close();
});

test('project research creation derives supported profile, is idempotent and retains ownership on retry', async t => {
  const { app, store } = await createApp(mkdtempSync(join(tmpdir(), 'project-research-api-')));
  t.after(() => app.close());
  const categories = (await app.inject({ method: 'GET', url: '/api/categories', headers })).json() as Category[];
  const shampoo = categories.find(item => item.code === 'shampoo')!;
  const personalCare = categories.find(item => item.code === 'personal-care')!;
  const createProject = async (categoryId: string, name: string) => {
    const response = await app.inject({ method: 'POST', url: '/api/product-projects', headers, payload: { categoryId, projectType: 'NEW_PRODUCT', name, objective: '核对市场需求', positioning: '', constraints: [], notes: '' } });
    assert.equal(response.statusCode, 201, response.body);
    return (response.json() as ProjectDetail).project.id;
  };
  const projectId = await createProject(shampoo.id, '洗发水研究项目');
  const otherId = await createProject(personalCare.id, '其他个护项目');
  const global = await app.inject({ method: 'POST', url: '/api/market-research-jobs', headers, payload: { sourcePlatform: 'jd', collectionProfile: 'shampoo', targetCount: 50, maxPages: 10 } });
  assert.equal(global.statusCode, 201, global.body);
  assert.equal((global.json() as MarketResearchJob).initiatingProjectId, null);
  const key = randomUUID();
  const submit = (id: string, targetCount: number, idempotencyKey = key) => app.inject({ method: 'POST', url: `/api/product-projects/${id}/market-research-jobs`, headers: { ...headers, 'idempotency-key': idempotencyKey }, payload: { targetCount } });
  assert.equal((await submit(otherId, 50)).statusCode, 409);
  const created = await submit(projectId, 50);
  assert.equal(created.statusCode, 201, created.body);
  const job = created.json() as MarketResearchJob;
  assert.equal(job.initiatingProjectId, projectId);
  assert.equal(job.sourcePlatform, 'jd');
  assert.equal(job.collectionProfile, 'shampoo');
  assert.equal(job.maxPages, 10);
  assert.equal((await submit(projectId, 50)).statusCode, 200);
  assert.equal((await submit(projectId, 60)).statusCode, 409);
  const listed = (await app.inject({ method: 'GET', url: `/api/product-projects/${projectId}/market-research-jobs`, headers })).json() as MarketResearchJob[];
  assert.deepEqual(listed.map(item => item.id), [job.id]);
  const globalList = (await app.inject({ method: 'GET', url: '/api/market-research-jobs', headers })).json() as MarketResearchJob[];
  assert.equal(globalList.length, 2);
  assert.equal(globalList.find(item => item.id === global.json().id)?.initiatingProjectId, null);
  store.db.prepare("UPDATE market_research_jobs SET state='FAILED',failed_stage='COLLECTING' WHERE id=?").run(job.id);
  const retried = await app.inject({ method: 'POST', url: `/api/market-research-jobs/${job.id}/retry`, headers, payload: {} });
  assert.equal(retried.statusCode, 200, retried.body);
  assert.equal((retried.json() as MarketResearchJob).initiatingProjectId, projectId);
  assert.equal(Number(store.db.prepare('SELECT count(*) count FROM market_research_jobs WHERE initiating_project_id=?').get(projectId)!.count), 1);
  assert.deepEqual(store.db.prepare('PRAGMA foreign_key_check').all(), []);
});

test('a user can establish the verified cleanser category before starting its research', async t => {
  const {app,store}=await createApp(mkdtempSync(join(tmpdir(),'cleanser-category-')));
  t.after(()=>app.close());
  const unavailable=await app.inject({method:'POST',url:'/api/market-research-jobs',headers,payload:{sourcePlatform:'jd',collectionProfile:'facial_cleanser',targetCount:20,maxPages:10}});
  assert.equal(unavailable.statusCode,409);
  const created=await app.inject({method:'POST',url:'/api/categories',headers,payload:{name:'洗面奶',parentId:null,preset:'facial_cleanser'}});
  assert.equal(created.statusCode,201,created.body);
  assert.equal(created.json().code,'facial-cleanser');
  assert.equal((await app.inject({method:'POST',url:'/api/categories',headers,payload:{name:'洗面奶',parentId:null,preset:'facial_cleanser'}})).statusCode,409);
  const research=await app.inject({method:'POST',url:'/api/market-research-jobs',headers,payload:{sourcePlatform:'jd',collectionProfile:'facial_cleanser',targetCount:20,maxPages:10}});
  assert.equal(research.statusCode,201,research.body);
  assert.equal((research.json() as MarketResearchJob).collectionProfile,'facial_cleanser');
  const project=await app.inject({method:'POST',url:'/api/product-projects',headers,payload:{categoryId:created.json().id,projectType:'NEW_PRODUCT',name:'洁面项目',objective:'验证洁面样本',positioning:'',constraints:[],notes:''}});
  assert.equal(project.statusCode,201,project.body);
  const projectId=(project.json() as ProjectDetail).project.id;
  const projectResearch=await app.inject({method:'POST',url:`/api/product-projects/${projectId}/market-research-jobs`,headers:{...headers,'idempotency-key':randomUUID()},payload:{targetCount:20}});
  assert.equal(projectResearch.statusCode,201,projectResearch.body);
  assert.equal((projectResearch.json() as MarketResearchJob).collectionProfile,'facial_cleanser');
  assert.equal((projectResearch.json() as MarketResearchJob).initiatingProjectId,projectId);
  assert.deepEqual(store.db.prepare('PRAGMA foreign_key_check').all(),[]);
});

test('market analysis quota failure resumes from saved batch with a selected configured model', async t => {
  const workingDirectory=process.cwd();
  process.chdir(mkdtempSync(join(tmpdir(),'project-research-model-config-')));
  t.after(()=>process.chdir(workingDirectory));
  const previous = process.env.COMMERCE_COPY_MODEL;
  process.env.COMMERCE_COPY_MODEL = 'qwen3.6-plus-2026-04-02';
  t.after(() => previous === undefined ? delete process.env.COMMERCE_COPY_MODEL : process.env.COMMERCE_COPY_MODEL = previous);
  const { app, store } = await createApp(mkdtempSync(join(tmpdir(), 'market-model-retry-')));
  t.after(() => app.close());
  const created = await app.inject({ method: 'POST', url: '/api/market-research-jobs', headers, payload: { sourcePlatform: 'jd', collectionProfile: 'shampoo', targetCount: 20, maxPages: 10 } });
  assert.equal(created.statusCode, 201, created.body);
  const id = (created.json() as MarketResearchJob).id;
  const product = { 商品标题: '样本洗发水', 商品链接: 'https://example.com/item', 品牌: '测试牌', 规格: '500ml', 店铺: '测试店', 榜单数值: '1', 时间证据: '2026-09-29', 类目: '洗发水', 价格: '39', 卖点原文: '蓬松' } as Record<string, string>;
  const batch = await app.inject({ method: 'POST', url: '/api/market/batches', headers, payload: { batch: { name: '分析恢复样本', source: 'JD Union Jingfen selected pools', platform: '京东', periodStart: '2026-09-29', periodEnd: '2026-09-29', metricName: '京东联盟30天SKU引单量', metricUnit: '引单' }, csv: csvText([[...columns], columns.map(column => product[column] ?? '')]) } });
  assert.equal(batch.statusCode, 201, batch.body);
  store.db.prepare("UPDATE market_research_jobs SET state='FAILED',failed_stage='ANALYZING',error_code='PROVIDER_REJECTED',manifest_data=?,market_batch_id=?,next_run_at=? WHERE id=?").run(JSON.stringify({ raw_count: 180, normalized_json_path: 'saved.json' }), batch.json().id, 9_007_199_254_740_991, id);
  const options = await app.inject({ method: 'GET', url: '/api/market-research-models', headers });
  assert.ok(options.json().lightModels.includes('qwen3.8-max'));
  assert.ok(!options.json().lightModels.includes('qwen3.6-plus-2026-04-02'));
  const rejected = await app.inject({ method: 'POST', url: `/api/market-research-jobs/${id}/retry`, headers, payload: { lightModelId: 'unconfigured-model' } });
  assert.equal(rejected.statusCode, 409);
  const retried = await app.inject({ method: 'POST', url: `/api/market-research-jobs/${id}/retry`, headers, payload: { lightModelId: 'qwen3.8-max' } });
  assert.equal(retried.statusCode, 200, retried.body);
  const job = retried.json() as MarketResearchJob;
  assert.equal(job.failedStage, 'ANALYZING');
  assert.equal(job.marketBatchId !== null, true);
  assert.equal(job.manifestData.analysisLightModelId, 'qwen3.8-max');
  assert.equal(job.manifestData.raw_count, 180);
  store.db.prepare("UPDATE market_research_jobs SET next_run_at=?,error_code='MODEL_NOT_CONFIGURED' WHERE id=?").run(9_007_199_254_740_991,id);
  const automatic = await app.inject({ method: 'POST', url: `/api/market-research-jobs/${id}/retry`, headers, payload: {} });
  assert.equal(automatic.statusCode,200,automatic.body);
  assert.equal((automatic.json() as MarketResearchJob).manifestData.analysisLightModelId,null);
  assert.equal((automatic.json() as MarketResearchJob).marketBatchId,job.marketBatchId);
  await processMarketResearchJob(store,id,async (_preview,options)=>{
    options?.onRun?.({capability:'TEXT_NORMALIZE',provider:'bailian',model:'qwen3.7-flash',modelVersion:null,requestMode:'json_schema',requestId:'provider-request',errorCode:'PROVIDER_QUOTA_EXHAUSTED',errorCategory:'NON_RETRYABLE_CONFIG',safeMessage:'当前模型额度不足',status:'FAILED',fallbackReason:null});
    throw new AppError('PROVIDER_QUOTA_EXHAUSTED','当前模型额度不足',409);
  });
  const after=store.db.prepare('SELECT state,failed_stage,market_batch_id,manifest_data FROM market_research_jobs WHERE id=?').get(id)!;
  assert.equal(after.state,'FAILED');assert.equal(after.failed_stage,'ANALYZING');assert.equal(after.market_batch_id,job.marketBatchId);
  assert.equal(JSON.parse(String(after.manifest_data)).aiRuns[0].requestId,'provider-request');
  assert.deepEqual(store.db.prepare('PRAGMA foreign_key_check').all(), []);
});

test('project research candidates require review and explicit inclusion before changing project evidence', async t => {
  const { app, store } = await createApp(mkdtempSync(join(tmpdir(), 'project-research-return-')));
  t.after(() => app.close());
  const categories = (await app.inject({ method: 'GET', url: '/api/categories', headers })).json() as Category[];
  const shampoo = categories.find(item => item.code === 'shampoo')!;
  const createdProject = await app.inject({ method: 'POST', url: '/api/product-projects', headers, payload: { projectType: 'NEW_PRODUCT', categoryId: shampoo.id, name: '研究回流项目', objective: '验证现有洗护需求', positioning: '', constraints: [], notes: '' } });
  assert.equal(createdProject.statusCode, 201, createdProject.body);
  const projectId = (createdProject.json() as ProjectDetail).project.id;
  const createdJob = await app.inject({ method: 'POST', url: `/api/product-projects/${projectId}/market-research-jobs`, headers: { ...headers, 'idempotency-key': randomUUID() }, payload: { targetCount: 50 } });
  assert.equal(createdJob.statusCode, 201, createdJob.body);
  const jobId = (createdJob.json() as MarketResearchJob).id;
  const values = { 商品标题: '控油蓬松洗发水', 商品链接: 'https://example.com/product', 品牌: '测试牌', 规格: '500ml', 店铺: '测试店', 榜单数值: '1', 时间证据: '2026-09-21', 类目: '洗发水', 价格: '39.9', 卖点原文: '控油 蓬松' } as Record<string, string>;
  const row = columns.map(column => values[column] ?? '');
  const imported = await app.inject({ method: 'POST', url: '/api/market/batches', headers, payload: { batch: { name: '回流测试样本', source: 'JD Union Jingfen selected pools', platform: '京东', periodStart: '2026-09-21', periodEnd: '2026-09-21', metricName: '京东联盟30天SKU引单量', metricUnit: '引单' }, csv: csvText([[...columns], row]) } });
  assert.equal(imported.statusCode, 201, imported.body);
  const batchId = imported.json().id as string;
  store.db.prepare('UPDATE market_research_jobs SET market_batch_id=?,state=? WHERE id=?').run(batchId, 'ANALYZING', jobId);
  const runner = async (preview: OpportunityPreview) => {
    const evidenceId = preview.included[0]!.id;
    return { output: { facts: [], inferences: [], opportunities: [{ name: '控油洗发水机会候选', summary: '仅代表当前样本，等待人工核对。', price_band: '30–50元', specifications: ['500ml'], core_basis: [{ text: '控油卖点出现', evidence_record_ids: [evidenceId] }], selling_points: [{ term: '控油', category: '功效', evidence_record_ids: [evidenceId] }], risks: [], missing_data: ['更多样本'], replicability: 'MEDIUM' as const, replicability_reason: '仍需核对配方', evidence_record_ids: [evidenceId] }], risks: [], missing_data: ['更多样本'] }, textSignals: { selling_point_groups: [] }, metadata: { modelId: 'test', modelVersion: 'test', requestId: 'test-request', promptVersion: 'market-opportunity-v3' as const, fallbackUsed: false, lightModelId: 'test-flash', lightModelVersion: 'test', lightRequestId: 'test-light-request' } };
  };
  const ids = await createMarketResearchOpportunities(store, batchId, shampoo.id, jobId, runner);
  assert.equal(ids.length, 1);
  store.db.prepare('UPDATE market_research_jobs SET state=?,opportunity_count=? WHERE id=?').run('REVIEW_REQUIRED', ids.length, jobId);
  assert.equal(((await app.inject({ method: 'GET', url: `/api/product-projects/${projectId}`, headers })).json() as ProjectDetail).evidence.length, 0);
  const candidate = (await app.inject({ method: 'GET', url: `/api/product-opportunities/${ids[0]}`, headers })).json() as ProductOpportunity;
  assert.equal(candidate.status, 'DRAFT');
  assert.equal(store.db.prepare("SELECT json_extract(analysis_data,'$.marketResearchJobId') job_id FROM product_opportunities WHERE id=?").get(candidate.id)!.job_id, jobId);
  const reviewed = await app.inject({ method: 'POST', url: `/api/product-opportunities/${candidate.id}/review`, headers, payload: { decision: 'APPROVED', reviewer: '测试审核人', note: '核对样本范围与来源后通过' } });
  assert.equal(reviewed.statusCode, 200, reviewed.body);
  assert.equal(((await app.inject({ method: 'GET', url: `/api/product-projects/${projectId}`, headers })).json() as ProjectDetail).evidence.length, 0);
  const included = await app.inject({ method: 'POST', url: `/api/product-projects/${projectId}/opportunities`, headers, payload: { opportunityId: candidate.id, note: '人工确认后纳入发起项目' } });
  assert.equal(included.statusCode, 201, included.body);
  assert.equal((await app.inject({ method: 'POST', url: `/api/product-projects/${projectId}/opportunities`, headers, payload: { opportunityId: candidate.id, note: '重复纳入' } })).statusCode, 200);
  const detail = (await app.inject({ method: 'GET', url: `/api/product-projects/${projectId}`, headers })).json() as ProjectDetail;
  assert.equal(detail.evidence.filter(item => item.id === candidate.evidenceId).length, 1);
  assert.equal(detail.events.filter(item => item.eventType === 'OPPORTUNITY_LINKED').length, 1);
  assert.equal(((await app.inject({ method: 'GET', url: `/api/product-opportunities/${candidate.id}`, headers })).json() as ProductOpportunity).status, 'READY');
  assert.equal((await app.inject({ method: 'POST', url: `/api/market-research-jobs/${jobId}/complete`, headers, payload: {} })).statusCode, 200);
  assert.deepEqual(store.db.prepare('PRAGMA foreign_key_check').all(), []);
});
