import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { setTimeout as wait } from 'node:timers/promises';
import { Store } from './store.js';
import { processMarketResearchJob } from './market-research.js';
import { processMarketMonitoringRun } from './market-monitoring.js';
const store=new Store(resolve('.runtime')),owner=randomUUID();let closing=false;
process.on('SIGINT',()=>{closing=true});process.on('SIGTERM',()=>{closing=true});
const configuredDays=Number(process.env.COMMERCE_MARKET_MONITORING_SCHEDULE_DAYS??0);
if(configuredDays!==0&&(!Number.isInteger(configuredDays)||configuredDays<7||configuredDays>90))throw new Error('监控周期必须为 7–90 天；不设置则不自动采集');
function schedule(){if(!configuredDays)return;const latest=store.db.prepare("SELECT captured_at,created_at FROM market_monitoring_runs ORDER BY created_at DESC LIMIT 1").get();if(latest&&Date.now()-Date.parse(String(latest.captured_at??latest.created_at))<configuredDays*86_400_000)return;const pending=store.db.prepare("SELECT id FROM market_monitoring_runs WHERE state IN ('CREATED','COLLECTING','NORMALIZING','IMPORTING','DETECTING') LIMIT 1").get();if(pending)return;const id=randomUUID(),time=new Date().toISOString();store.db.prepare(`INSERT INTO market_monitoring_runs (id,source_platform,collection_profile,source_scope,pool_scope,page_size,max_pages,trigger_type,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(id,'jd','shampoo','jd_union_jingfen_multi_pool',JSON.stringify({eliteIds:[22,25,27,28],maxPages:10,pageSize:50,categoryIds:[16750,16751,16756,16761]}),50,10,'SCHEDULED','CREATED',time,time);}
while(!closing){schedule();const stamp=Date.now();const research=store.db.prepare("SELECT id,created_at FROM market_research_jobs WHERE state IN ('CREATED','COLLECTING','NORMALIZING','IMPORTING','ANALYZING','FAILED') AND next_run_at<=? AND (lease_until IS NULL OR lease_until<?) ORDER BY created_at LIMIT 1").get(stamp,stamp);const monitoring=store.db.prepare("SELECT id,created_at FROM market_monitoring_runs WHERE state IN ('CREATED','COLLECTING','NORMALIZING','IMPORTING','DETECTING','FAILED') AND next_run_at<=? AND (lease_until IS NULL OR lease_until<?) ORDER BY created_at LIMIT 1").get(stamp,stamp);const kind=monitoring&&(!research||String(monitoring.created_at)<String(research.created_at))?'monitoring':'research';const row=kind==='monitoring'?monitoring:research;if(!row){await wait(750);continue;}const id=String(row.id);if(kind==='monitoring'){const claimed=store.db.prepare('UPDATE market_monitoring_runs SET lease_owner=?,lease_until=? WHERE id=? AND (lease_until IS NULL OR lease_until<?)').run(owner,Date.now()+20*60_000,id,Date.now());if(Number(claimed.changes)!==1)continue;await processMarketMonitoringRun(store,id);store.db.prepare('UPDATE market_monitoring_runs SET lease_owner=NULL,lease_until=NULL WHERE id=? AND lease_owner=?').run(id,owner);}else{const claimed=store.db.prepare('UPDATE market_research_jobs SET lease_owner=?,lease_until=?,lease_epoch=lease_epoch+1 WHERE id=? AND (lease_until IS NULL OR lease_until<?)').run(owner,Date.now()+20*60_000,id,Date.now());if(Number(claimed.changes)!==1)continue;await processMarketResearchJob(store,id);store.db.prepare('UPDATE market_research_jobs SET lease_owner=NULL,lease_until=NULL WHERE id=? AND lease_owner=?').run(id,owner);}}
store.close();
