import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { adaptJdJingfen } from '../../packages/contracts/jd-market-adapter.js';
import { AppError, type Store } from './store.js';
import { importJdMarketBatch } from './jd-market-import.js';
import { runCollector } from './market-research.js';
import { aggregateChanges, monitorSignalRules, signalChanges, snapshotFacts, type AggregateChange } from './market-monitoring-facts.js';
import { recordedStructuredRun } from './ai-inference-runs.js';

const poolIds=[22,25,27,28];
const now=()=>new Date().toISOString();
type Row=Record<string,any>;
// SQLite's positional binding overload rejects values built from validated JSON at compile time.
const db=(store:Store)=>store.db as any;
type Source={batch_id:string;collected_at:string;source_scope:string;relevant_category_ids:number[];pool_results:Array<{elite_id:number;requested_pages:number;raw_product_count:number;api_error_count:number;retry_count:number}>;items:unknown[]};
const sourceSchema=z.object({batch_id:z.string().min(1),collected_at:z.string().min(1),source_scope:z.literal('jd_union_jingfen_multi_pool'),relevant_category_ids:z.array(z.number().int()),pool_results:z.array(z.object({elite_id:z.number().int(),requested_pages:z.number().int().nonnegative(),raw_product_count:z.number().int().nonnegative(),api_error_count:z.number().int().nonnegative(),retry_count:z.number().int().nonnegative()}).passthrough()),items:z.array(z.unknown())}).passthrough();
const signalSchema=z.object({interpretation:z.string().min(1).max(600),possibleOpportunity:z.string().max(600),uncertainty:z.string().min(1).max(600),evidenceEntryIds:z.array(z.string().uuid()).max(8)}).strict();
const signalJsonSchema={type:'object',additionalProperties:false,required:['interpretation','possibleOpportunity','uncertainty','evidenceEntryIds'],properties:{interpretation:{type:'string'},possibleOpportunity:{type:'string'},uncertainty:{type:'string'},evidenceEntryIds:{type:'array',items:{type:'string'}}}};
function parse(value:unknown){return JSON.parse(String(value)) as Row}
function publicRun(row:Row,store?:Store){return {id:String(row.id),sourcePlatform:String(row.source_platform),collectionProfile:String(row.collection_profile),sourceScope:String(row.source_scope),poolScope:parse(row.pool_scope),pageSize:Number(row.page_size),maxPages:Number(row.max_pages),triggerType:String(row.trigger_type),state:String(row.state),marketBatchId:row.market_batch_id?String(row.market_batch_id):null,capturedAt:row.captured_at?String(row.captured_at):null,collectionData:parse(row.collection_data),comparisonData:store?validatedMonitoringComparison(store,row):parse(row.comparison_data),errorCode:row.error_code?String(row.error_code):null,retryCount:Number(row.retry_count),createdAt:String(row.created_at)};}
function setState(store:Store,id:string,state:string,extra:Record<string,unknown>={}){const allowed=new Set(['market_batch_id','captured_at','collection_data','comparison_data','pool_scope','error_code','retry_count','next_run_at']);for(const key of Object.keys(extra))if(!allowed.has(key))throw new Error(`unexpected monitoring field ${key}`);const fields=['state=?','updated_at=?',...Object.keys(extra).map(key=>`${key}=?`)];db(store).prepare(`UPDATE market_monitoring_runs SET ${fields.join(',')} WHERE id=?`).run(state,now(),...Object.values(extra).map(value=>value&&typeof value==='object'?JSON.stringify(value):value),id);}
function readSource(path:string):Source{try{return sourceSchema.parse(JSON.parse(readFileSync(path,'utf8')))}catch{throw new AppError('MONITOR_SOURCE_INVALID','采集结果结构不符合已验证范围',409)}}
function scope(source:Source,maxPages:number){return {eliteIds:source.pool_results.map(pool=>pool.elite_id).sort((a,b)=>a-b),maxPages,pageSize:50,categoryIds:[...source.relevant_category_ids].sort((a,b)=>a-b)};}
function collection(source:Source,expectedCount:number){const errors=source.pool_results.reduce((sum,pool)=>sum+pool.api_error_count,0);const complete=source.pool_results.length===poolIds.length&&source.pool_results.every(pool=>poolIds.includes(pool.elite_id)&&pool.requested_pages>0&&pool.requested_pages<=10&&pool.api_error_count===0)&&source.items.length===expectedCount;return {complete,apiErrors:errors,pools:source.pool_results.map(pool=>({eliteId:pool.elite_id,pages:pool.requested_pages,rawCount:pool.raw_product_count,apiErrors:pool.api_error_count,retries:pool.retry_count})),rawCount:source.pool_results.reduce((sum,pool)=>sum+pool.raw_product_count,0),validCount:source.items.length};}
export function filterFingerprint(reportPath:string){const report=readFileSync(reportPath,'utf8'),start=report.indexOf('筛选要求'),end=report.indexOf('## 产物',start);if(start>=0&&end>start)return createHash('sha256').update(report.slice(start,end).trim()).digest('hex');const declared=report.split(/\r?\n/).find(line=>line.startsWith('筛选只使用实际返回的类目与标题；'));return declared?createHash('sha256').update(`collector-filter-declaration-v1:${declared.trim()}`).digest('hex'):null;}
export function monitoringResumeStage(row:Row){const data=parse(row.collection_data);if(row.market_batch_id)return 'DETECTING';if(data.adapted)return 'IMPORTING';if(typeof data.normalized_json_path==='string')return 'NORMALIZING';if(data.failedStage==='CREATED'||data.failedStage==='COLLECTING')return 'COLLECTING';throw new AppError('RECOVERY_STAGE_UNKNOWN','无法确认可恢复阶段，请核对已保存的采集产物',409);}
function comparable(a:Row,b:Row){const x=parse(a.collection_data),y=parse(b.collection_data);const pages=(data:Row)=>JSON.stringify((data.pools as Row[]|undefined)?.map(pool=>[pool.eliteId,pool.pages]).sort((left,right)=>Number(left[0])-Number(right[0])));const scopeKnown=(data:Row)=>typeof data.filterFingerprint==='string'&&data.filterFingerprint.trim().length>0&&Array.isArray(data.pools)&&data.pools.length>0&&data.pools.every((pool:Row)=>Number.isInteger(pool.eliteId)&&Number.isInteger(pool.pages)&&Number(pool.pages)>0);return scopeKnown(x)&&scopeKnown(y)&&a.source_platform===b.source_platform&&a.collection_profile===b.collection_profile&&a.source_scope===b.source_scope&&a.pool_scope===b.pool_scope&&x.complete===true&&y.complete===true&&x.filterFingerprint===y.filterFingerprint&&pages(x)===pages(y);}
export function validatedMonitoringComparison(store:Store,row:Row){
  const saved=parse(row.comparison_data);
  if(saved.comparable!==true)return saved;
  const baseline=saved.baselineRunId?db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(saved.baselineRunId):null;
  if(!baseline||baseline.id===row.id||baseline.state!=='COMPLETED'||row.state!=='COMPLETED'||!baseline.captured_at||!row.captured_at||String(baseline.captured_at)>=String(row.captured_at)||!comparable(row,baseline))return {comparable:false,reason:'历史比较的采集范围与当前规则不一致，不展示旧变化结果',changes:[],signals:[]};
  return saved;
}
function currentEntries(store:Store,batchId:string,change:AggregateChange){if(!['KEYWORD_DISTRIBUTION_CHANGED','BRAND_STRUCTURE_CHANGED','SHOP_STRUCTURE_CHANGED','PRICE_BAND_CHANGED'].includes(change.type))return [];const rows=db(store).prepare('SELECT id,normalized_data,source_metadata FROM market_entries WHERE batch_id=? ORDER BY row_number').all(batchId) as Row[];const name=change.key.split(':').slice(1).join(':');return rows.filter(row=>{const d=parse(row.normalized_data);if(change.type==='KEYWORD_DISTRIBUTION_CHANGED')return String(d.title??'').includes(name)||String(d.sellingPoints??'').includes(name);if(change.type==='BRAND_STRUCTURE_CHANGED')return d.brand===name;if(change.type==='SHOP_STRUCTURE_CHANGED')return d.shop===name;if(change.type==='PRICE_BAND_CHANGED'){const price=Number(parse(row.source_metadata).source_price);return Number.isFinite(price)&&(name==='30元以下'?price<30:name==='30–49元'?price>=30&&price<50:name==='50–99元'?price>=50&&price<100:price>=100)}return false}).slice(0,8).map(row=>String(row.id));}
export function detectMonitoringChanges(store:Store,id:string){const row=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id);if(!row||!row.market_batch_id)throw new AppError('SNAPSHOT_MISSING','当前监控没有可比较的批次',409);if(parse(row.collection_data).complete!==true)return {comparable:false,reason:'采集不完整，禁止跨期比较',changes:[],signals:[]};const previous=db(store).prepare("SELECT * FROM market_monitoring_runs WHERE id<>? AND state='COMPLETED' AND captured_at<? ORDER BY captured_at DESC LIMIT 30").all(id,row.captured_at).find((candidate:Row)=>comparable(candidate,row));if(!previous)return {comparable:false,reason:'尚无相同来源、范围和筛选口径的完整快照',changes:[],signals:[]};const before=snapshotFacts(store,String(previous.market_batch_id)),after=snapshotFacts(store,String(row.market_batch_id)),changes=aggregateChanges(before,after),important=signalChanges(changes,before.sampleSize);const createdAt=now();store.transaction(()=>{for(const change of important){const evidence=currentEntries(store,String(row.market_batch_id),change);db(store).prepare(`INSERT OR IGNORE INTO market_signals (id,monitoring_run_id,baseline_run_id,signal_key,signal_type,rule_version,fact_data,evidence_data,priority,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(randomUUID(),id,previous.id,change.key,change.type,'aggregate-v1',JSON.stringify(change),JSON.stringify({currentEntryIds:evidence,baselineBatchId:previous.market_batch_id,currentBatchId:row.market_batch_id}),change.type==='MEDIAN_PRICE_CHANGED'||change.type==='SAMPLE_SIZE_CHANGED'?'HIGH':'NORMAL',createdAt)}});return {comparable:true,baselineRunId:String(previous.id),changes,signals:important,productIdentity:'UNRELIABLE',note:'京粉 itemId 跨期不稳定；商品新增、退出及逐商品变化均不可判定。'};}
export function registerVerifiedHistoricalSnapshots(store:Store){const jobs=db(store).prepare("SELECT * FROM market_research_jobs WHERE source_platform='jd' AND collection_profile='shampoo' AND market_batch_id IS NOT NULL ORDER BY created_at").all();let registered=0;for(const job of jobs){if(db(store).prepare('SELECT id FROM market_monitoring_runs WHERE source_research_job_id=?').get(job.id))continue;const manifest=parse(job.manifest_data);if(typeof manifest.normalized_json_path!=='string'||typeof manifest.report_path!=='string'||!existsSync(manifest.normalized_json_path)||!existsSync(manifest.report_path))continue;const source=readSource(manifest.normalized_json_path),check=collection(source,Number(job.valid_count));if(!check.complete||JSON.stringify(scope(source,Number(job.max_pages)).eliteIds)!==JSON.stringify(poolIds))continue;const count=Number(db(store).prepare('SELECT count(*) n FROM market_entries WHERE batch_id=?').get(job.market_batch_id)?.n??0);if(count!==source.items.length)continue;const fingerprint=filterFingerprint(manifest.report_path),id=randomUUID(),time=now();db(store).prepare(`INSERT INTO market_monitoring_runs (id,source_platform,collection_profile,source_scope,pool_scope,page_size,max_pages,trigger_type,state,market_batch_id,source_research_job_id,captured_at,collection_data,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,'jd','shampoo',source.source_scope,JSON.stringify(scope(source,Number(job.max_pages))),50,job.max_pages,'HISTORICAL','COMPLETED',job.market_batch_id,job.id,source.collected_at,JSON.stringify({...check,filterFingerprint:fingerprint,rawRoot:manifest.raw_root,reportPath:manifest.report_path}),time,time);registered++;}const completed=db(store).prepare("SELECT id FROM market_monitoring_runs WHERE state='COMPLETED' ORDER BY captured_at DESC LIMIT 1").get();if(completed){const result=detectMonitoringChanges(store,String(completed.id));db(store).prepare('UPDATE market_monitoring_runs SET comparison_data=? WHERE id=?').run(JSON.stringify(result),completed.id);}return {registered,total:jobs.length};}
export async function processMarketMonitoringRun(store:Store,id:string){const row=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id);if(!row)return;try{let state=String(row.state),data=parse(row.collection_data);if(state==='FAILED'){state=monitoringResumeStage(row);setState(store,id,state,{error_code:null});}if(state==='CREATED'||state==='COLLECTING'){setState(store,id,'COLLECTING',{error_code:null});const manifest=await runCollector({id,maxPages:Number(row.max_pages),targetCount:100});data={...manifest};setState(store,id,'NORMALIZING',{collection_data:data});state='NORMALIZING';}
    if(state==='NORMALIZING'){const source=readSource(String(data.normalized_json_path));const adapted=adaptJdJingfen(source,String(data.raw_root));adapted.batch.name=`${adapted.batch.name} · 监控 ${source.batch_id}`;data={...data,adapted,check:collection(source,source.items.length),capturedAt:source.collected_at,poolScope:scope(source,Number(row.max_pages)),filterFingerprint:filterFingerprint(String(data.report_path))};setState(store,id,'IMPORTING',{collection_data:data});state='IMPORTING';}
    if(state==='IMPORTING'){let imported;try{imported=importJdMarketBatch(store,data.adapted);}catch(error){const existing=db(store).prepare('SELECT id FROM market_batches WHERE name=?').get((data.adapted as {batch:{name:string}}).batch.name);if(!existing)throw error;imported={id:String(existing.id)};}setState(store,id,'DETECTING',{market_batch_id:imported.id,captured_at:data.capturedAt,pool_scope:data.poolScope,collection_data:{...data.check,filterFingerprint:data.filterFingerprint,rawRoot:data.raw_root,reportPath:data.report_path}});state='DETECTING';}
    if(state==='DETECTING'){const current=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id)!;if(parse(current.collection_data).complete!==true){setState(store,id,'PARTIAL');return;}const comparison=detectMonitoringChanges(store,id);setState(store,id,'COMPLETED',{comparison_data:comparison});}
  }catch(error){const current=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id)!;setState(store,id,'FAILED',{error_code:error instanceof AppError?error.code:'MONITORING_FAILED',collection_data:{...parse(current.collection_data),failedStage:current.state},next_run_at:9_007_199_254_740_991});}}
export function registerMarketMonitoring(app:FastifyInstance,store:Store){
  app.get('/api/market-monitoring/runs',async()=>db(store).prepare('SELECT * FROM market_monitoring_runs ORDER BY created_at DESC LIMIT 50').all().map((row:Row)=>publicRun(row,store)));
  app.post('/api/market-monitoring/runs',async(request,reply)=>{const input=z.object({triggerType:z.literal('MANUAL').default('MANUAL')}).strict().parse(request.body??{});const active=db(store).prepare("SELECT * FROM market_monitoring_runs WHERE state IN ('CREATED','COLLECTING','NORMALIZING','IMPORTING','DETECTING') ORDER BY created_at DESC LIMIT 1").get();if(active)return reply.code(200).send(publicRun(active));const id=randomUUID(),time=now();db(store).prepare(`INSERT INTO market_monitoring_runs (id,source_platform,collection_profile,source_scope,pool_scope,page_size,max_pages,trigger_type,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(id,'jd','shampoo','jd_union_jingfen_multi_pool',JSON.stringify({eliteIds:poolIds,maxPages:10,pageSize:50,categoryIds:[16750,16751,16756,16761]}),50,10,input.triggerType,'CREATED',time,time);return reply.code(201).send(publicRun(db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id)!));});
  app.post('/api/market-monitoring/register-history',async()=>registerVerifiedHistoricalSnapshots(store));
  app.post('/api/market-monitoring/runs/:id/retry',async request=>{const id=z.object({id:z.string().uuid()}).parse(request.params).id,row=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id);if(!row)throw new AppError('NOT_FOUND','监控运行不存在',404);if(row.state!=='FAILED')throw new AppError('RUN_NOT_FAILED','只有失败运行可重试',409);setState(store,id,monitoringResumeStage(row),{retry_count:Number(row.retry_count)+1,next_run_at:0,error_code:null});return publicRun(db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(id)!);});
  app.get('/api/market-monitoring/dashboard',async request=>{const filter=z.object({priceMin:z.coerce.number().nonnegative().optional(),priceMax:z.coerce.number().nonnegative().optional(),keyword:z.string().trim().max(30).optional(),brand:z.string().trim().max(100).optional(),shop:z.string().trim().max(150).optional()}).strict().parse(request.query);if(filter.priceMin!==undefined&&filter.priceMax!==undefined&&filter.priceMin>filter.priceMax)throw new AppError('INVALID_PRICE_RANGE','价格下限不能大于上限',400);const row=db(store).prepare("SELECT * FROM market_monitoring_runs WHERE state='COMPLETED' ORDER BY captured_at DESC LIMIT 1").get();if(!row)return {current:null,previous:null,facts:null,sliceFacts:null,comparison:null,signals:[],signalRules:monitorSignalRules()};const comparison=validatedMonitoringComparison(store,row),previous=comparison.baselineRunId?db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(comparison.baselineRunId):null;return {current:publicRun(row,store),previous:previous?publicRun(previous,store):null,facts:snapshotFacts(store,String(row.market_batch_id)),sliceFacts:Object.keys(filter).length?snapshotFacts(store,String(row.market_batch_id),filter):null,comparison,signalRules:monitorSignalRules(),signals:comparison.comparable!==true?[]:db(store).prepare('SELECT * FROM market_signals WHERE monitoring_run_id=? ORDER BY priority,created_at LIMIT 30').all(row.id).map((signal:Row)=>({id:String(signal.id),type:String(signal.signal_type),fact:parse(signal.fact_data),evidence:parse(signal.evidence_data),priority:String(signal.priority),reviewState:String(signal.review_state),inferenceRunId:signal.inference_run_id?String(signal.inference_run_id):null}))};});
  app.post('/api/market-monitoring/signals/:id/explain',async request=>{const id=z.object({id:z.string().uuid()}).parse(request.params).id,row=db(store).prepare('SELECT * FROM market_signals WHERE id=?').get(id);if(!row)throw new AppError('NOT_FOUND','市场信号不存在',404);const sourceRun=db(store).prepare('SELECT * FROM market_monitoring_runs WHERE id=?').get(row.monitoring_run_id);const comparison=sourceRun?validatedMonitoringComparison(store,sourceRun):null;if(!comparison||comparison.comparable!==true||comparison.baselineRunId!==row.baseline_run_id)throw new AppError('COMPARISON_NOT_RELIABLE','该信号的历史快照不再满足比较条件，不能作为可靠变化解释',409);if(row.inference_run_id){const saved=db(store).prepare('SELECT id,output_data FROM ai_inference_runs WHERE id=?').get(row.inference_run_id);if(saved?.output_data)return {runId:String(saved.id),output:parse(saved.output_data)};}const fact=parse(row.fact_data),evidence=parse(row.evidence_data),allowed=new Set((evidence.currentEntryIds as string[]|undefined)??[]);const result=await recordedStructuredRun(store,{task:'market_signal_interpretation',subjectType:'market_signal',subjectId:id,input:{fact,evidenceEntryIds:[...allowed],scope:'JD Union Jingfen selected pools；仅代表两次可比快照。itemId 跨期不稳定，不得推断商品进出；评论数不是销量，联盟引单不是京东全站销量。'},systemPrompt:'只解释程序已确认的市场信号，不重新计算数字，不宣称长期趋势或京东全站结论。解释必须带不确定性，引用只能使用给定 evidenceEntryIds。输出简短严格 JSON。',outputName:'market_signal_interpretation',jsonSchema:signalJsonSchema,validator:signalSchema});if(result.output.evidenceEntryIds.some(entryId=>!allowed.has(entryId)))throw new AppError('INVALID_AI_EVIDENCE','模型引用了范围外证据',409);db(store).prepare('UPDATE market_signals SET inference_run_id=? WHERE id=? AND inference_run_id IS NULL').run(result.id,id);return {runId:result.id,model:result.model,output:result.output};});
  app.post('/api/market-monitoring/signals/:id/review',async request=>{const id=z.object({id:z.string().uuid()}).parse(request.params).id;if(!db(store).prepare('SELECT id FROM market_signals WHERE id=?').get(id))throw new AppError('NOT_FOUND','市场信号不存在',404);db(store).prepare("UPDATE market_signals SET review_state='REVIEWED',reviewed_at=? WHERE id=? AND review_state='OPEN'").run(now(),id);return {id,reviewState:'REVIEWED'};});
}
