import { Select } from './components/Select.js';
import { usePresentationState } from './presentation-cache.js';
import { useEffect,useState } from 'react';
import { api,json } from './api.js';
import './market-monitoring.css';
import { useRoutedState } from './workspace-route.js';
import { InlineError, PageLoading } from './components/states.js';

type Dist={name:string;count:number};
type Facts={sampleSize:number;medianPrice:number|null;priceBands:Dist[];brands:Dist[];shops:Dist[];keywords:Dist[];coverage:Record<string,number>;couponStatus:string;itemIdentity:string};
type Change={key:string;type:string;label:string;before:number;after:number;delta:number};
type Run={id:string;state:string;marketBatchId:string|null;capturedAt:string|null;collectionData:{normalized_json_path?:string;failedStage?:string;complete?:boolean;apiErrors?:number;rawCount?:number;validCount?:number;pools?:Array<{eliteId:number;pages:number;rawCount:number;apiErrors:number}>};errorCode:string|null;triggerType:string};
type Signal={id:string;type:string;fact:Change;evidence:{currentEntryIds:string[];currentBatchId:string};priority:string;reviewState:string;inferenceRunId:string|null};
type Dashboard={current:Run|null;previous:Run|null;facts:Facts|null;sliceFacts:Facts|null;comparison:{comparable?:boolean;reason?:string;changes?:Change[];note?:string}|null;signals:Signal[];signalRules?:{sampleDelta:number;medianPriceDelta:number;medianPriceRatio:number;distributionDelta:number;distributionSampleRatio:number}};
type SliceFilter={priceMin:string;priceMax:string;keyword:string;brand:string;shop:string};
const emptyFilter:SliceFilter={priceMin:'',priceMax:'',keyword:'',brand:'',shop:''};
const labels:Record<string,string>={CREATED:'等待采集',COLLECTING:'采集中',NORMALIZING:'整理商品',IMPORTING:'保存快照',DETECTING:'计算变化',COMPLETED:'已完成',PARTIAL:'采集不完整',FAILED:'运行失败'};
const metricDefinitions=[['评论数','商品累计评论，不是销量。'],['联盟30天SKU引单','京东联盟口径的引单指标，不是京东全站销量。'],['佣金','推广激励，不代表消费者需求。'],['券后价','仅在券实际有效且符合使用条件时才可作为成交价；当前券状态尚未核实。'],['关键词覆盖','词语在当前有限样本商品标题中的出现数，不是搜索量。']];
function Distribution({title,items,total}:{title:string;items:Dist[];total:number}){return <div className="monitor-chart"><strong>{title}</strong>{items.slice(0,6).map(item=><div className="monitor-bar" key={item.name}><span>{item.name}</span><i style={{width:`${Math.max(2,100*item.count/Math.max(total,1))}%`}}/><b>{item.count}</b></div>)}</div>}
export function MarketMonitoringPanel({onBatch,onCurrentBatchId}:{onBatch:(id:string)=>void;onCurrentBatchId:(id:string|null)=>void}){
  const [selectedRun,setSelectedRun]=useRoutedState<string|null>('monitoringRun',null);
  const [data,setData]=useState<Dashboard|null>(null),[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[explanations,setExplanations]=useState<Record<string,{interpretation:string;possibleOpportunity:string;uncertainty:string}>>({});
  const [draft,setDraft]=usePresentationState<SliceFilter>('monitoring.draft',emptyFilter),[filter,setFilter]=usePresentationState<SliceFilter>('monitoring.filter',emptyFilter);
  async function load(){const query=new URLSearchParams(Object.entries(filter).filter(([,value])=>value.trim()));const path=`/market-monitoring/dashboard${query.size?`?${query}`:''}`;const [dashboard,history]=await Promise.all([api<Dashboard>(path),api<Run[]>('/market-monitoring/runs')]);setData(dashboard);setRuns(history);onCurrentBatchId(dashboard.current?.marketBatchId??null);}
  useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>void load().catch(()=>{}),5000);return()=>clearInterval(timer);},[filter]);
  async function action(path:string,body:unknown={}){setBusy(true);setError('');try{await api(path,json(body));await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function explain(id:string){setBusy(true);setError('');try{const result=await api<{output:{interpretation:string;possibleOpportunity:string;uncertainty:string}}>(`/market-monitoring/signals/${id}/explain`,json({}));setExplanations(value=>({...value,[id]:result.output}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const current=data?.current,facts=data?.facts,latest=runs.find(run=>run.id===selectedRun)??runs[0],working=runs.some(run=>['CREATED','COLLECTING','NORMALIZING','IMPORTING','DETECTING'].includes(run.state)),changes=data?.comparison?.changes??[],signals=data?.signals??[];
  return <section className="market-monitoring card"><header className="section-heading"><div><span className="eyebrow">JD UNION · 洗发水</span><h2>市场监控</h2><p className="muted">指定京粉商品池、每池最多 10 页；仅代表当前有限样本。</p></div><button className="primary" disabled={busy||!!working} onClick={()=>action('/market-monitoring/runs')}>采集新快照</button></header>
    {error&&<InlineError onRetry={()=>{setError('');void load().catch(e=>setError(e.message));}}>{error}</InlineError>}
    {!data&&!error&&<PageLoading>读取市场快照</PageLoading>}
    {working&&<p className="monitor-status">{labels[latest?.state??'CREATED']} · 京东联盟洗发水 · 刷新页面后仍可查看进度</p>}
    {latest?.state==='FAILED'&&<p className="notice-error">{latest.collectionData.normalized_json_path?'采集产物已保存，快照整理尚未完成。继续处理会复用已有文件。':'当前监控步骤未完成。'} <span>{latest.errorCode==='FILTER_SCOPE_UNKNOWN'?'筛选说明无法读取。':latest.errorCode==='RECOVERY_STAGE_UNKNOWN'?'恢复阶段无法确认，需核对保存产物。':latest.errorCode??'原因待查'}</span> <button disabled={busy} onClick={()=>action(`/market-monitoring/runs/${latest.id}/retry`)}>{latest.collectionData.normalized_json_path?'继续整理已保存数据':'重试当前步骤'}</button></p>}
    {latest?.state==='PARTIAL'&&<p className="notice warning">本次采集不完整，未参与跨期比较。</p>}
    {!current||!facts?<p className="muted">尚无完整市场快照。一次性市场研究及历史商品证据仍可在下方查看。</p>:<>
      <div className="monitor-summary"><div><small>当前快照</small><strong>{new Date(current.capturedAt??'').toLocaleString('zh-CN')}</strong></div><div><small>有效样本</small><strong>{facts.sampleSize}</strong></div><div><small>品牌 / 店铺</small><strong>{facts.brands.length} / {facts.shops.length}</strong></div><div><small>商品标价中位数</small><strong>{facts.medianPrice===null?'—':`¥${facts.medianPrice}`}</strong></div></div>
      <p className="monitor-brief"><strong>本期摘要：</strong>{data?.comparison?.comparable?changes.length?`与上次同范围快照相比，确认 ${changes.length} 项样本聚合变化；其中 ${signals.length} 项达到关注阈值。`:'与上次同范围快照相比，当前可计算的聚合指标未见变化。':data?.comparison?.reason??'目前只有一期完整快照。'}</p>
      <details className="monitor-details monitor-slice"><summary>按价格、关键词、品牌或店铺查看当前样本</summary><div className="monitor-slice-fields"><label>最低价<input type="number" min="0" value={draft.priceMin} onChange={event=>setDraft({...draft,priceMin:event.target.value})}/></label><label>最高价<input type="number" min="0" value={draft.priceMax} onChange={event=>setDraft({...draft,priceMax:event.target.value})}/></label><label>关键词<input value={draft.keyword} onChange={event=>setDraft({...draft,keyword:event.target.value})}/></label><label>品牌<Select value={draft.brand} onChange={event=>setDraft({...draft,brand:event.target.value})}><option value="">全部品牌</option>{facts.brands.map(item=><option key={item.name} value={item.name}>{item.name}</option>)}</Select></label><label>店铺<Select value={draft.shop} onChange={event=>setDraft({...draft,shop:event.target.value})}><option value="">全部店铺</option>{facts.shops.map(item=><option key={item.name} value={item.name}>{item.name}</option>)}</Select></label></div><div className="monitor-actions"><button onClick={()=>setFilter({...draft})}>查看子样本</button><button onClick={()=>{setDraft(emptyFilter);setFilter(emptyFilter)}}>清除筛选</button></div>{data?.sliceFacts&&<p className="monitor-slice-result">当前子样本：<strong>{data.sliceFacts.sampleSize}</strong> 条 · 标价中位数 <strong>{data.sliceFacts.medianPrice===null?'—':`¥${data.sliceFacts.medianPrice}`}</strong> · 品牌 {data.sliceFacts.brands.length} 个 · 店铺 {data.sliceFacts.shops.length} 个。统计由当前筛选结果重新计算。</p>}</details>
      <div className="monitor-charts"><Distribution title="价格带分布" items={facts.priceBands} total={facts.sampleSize}/><Distribution title="卖点 / 关键词覆盖" items={facts.keywords} total={facts.sampleSize}/></div>
      <details className="monitor-structure"><summary>查看品牌与店铺结构</summary><div className="monitor-charts"><Distribution title="品牌结构" items={facts.brands} total={facts.sampleSize}/><Distribution title="店铺结构" items={facts.shops} total={facts.sampleSize}/></div></details>
      {changes.length>0&&<div className="monitor-change"><h3>较上期主要变化</h3>{changes.length?<div className="monitor-change-list">{changes.slice(0,8).map(item=><p key={item.key}><span>{item.label}</span><strong>{item.before} → {item.after}</strong></p>)}</div>:<p className="muted">{data?.comparison?.reason??'当前可比较的聚合指标没有变化；不据此推断长期趋势。'}</p>}</div>}
      {signals.length>0&&<div className="monitor-signals"><h3>值得关注的市场信号</h3>{signals.length?signals.map(signal=><article key={signal.id}><strong>【市场事实】{signal.fact.label}：{signal.fact.before} → {signal.fact.after}</strong><p>为什么值得关注：变化达到当前监控规则阈值；需结合更多期数据验证。</p><small>【数据局限】仅代表指定京粉商品池。商品级身份不可判定。</small><div className="monitor-actions"><button onClick={()=>onBatch(signal.evidence.currentBatchId)}>查看商品证据</button><button disabled={busy} onClick={()=>explain(signal.id)}>查看 AI 分析</button>{signal.reviewState==='OPEN'&&<button disabled={busy} onClick={()=>action(`/market-monitoring/signals/${signal.id}/review`)}>标记已查看</button>}</div>{explanations[signal.id]&&<p>【AI分析】{explanations[signal.id]!.interpretation}；待验证：{explanations[signal.id]!.uncertainty}</p>}</article>):<p className="muted">当前没有达到关注阈值的信号；普通采集成功不会产生待办。</p>}</div>}
      <details className="monitor-details"><summary>查看采集完整性、指标定义和详细记录</summary><p>券是否有效尚未核实，暂不统计有效券商品。跨期无法可靠识别同一商品，当前只比较样本整体变化，不计算单件商品新增、退出或调价。</p><p>API 错误 {current.collectionData.apiErrors??0} · 原始商品 {current.collectionData.rawCount??'—'} · 有效商品 {current.collectionData.validCount??facts.sampleSize} · 关键字段覆盖：价格 {facts.coverage.price}/{facts.sampleSize}，品牌 {facts.coverage.brand}/{facts.sampleSize}，店铺 {facts.coverage.shop}/{facts.sampleSize}，评论 {facts.coverage.comments}/{facts.sampleSize}。</p><p>商品池：{current.collectionData.pools?.map(pool=>`${pool.eliteId}（${pool.pages} 页，${pool.rawCount} 条）`).join('、')??'范围记录缺失'}</p>{data.signalRules&&<p>关注阈值：样本数变化至少 {data.signalRules.sampleDelta} 条；标价中位数变化至少 ¥{data.signalRules.medianPriceDelta} 且达到 {Math.round(data.signalRules.medianPriceRatio*100)}%；品牌、店铺、关键词或价格带变化至少 {data.signalRules.distributionDelta} 条且样本占比变化达到 {Math.round(data.signalRules.distributionSampleRatio*100)}%。可由服务端配置调整。</p>}{metricDefinitions.map(([name,definition])=><p key={name}><strong>{name}：</strong>{definition}</p>)}<button onClick={()=>onBatch(current.marketBatchId!)}>查看完整商品记录与来源</button></details>
    </>}
  </section>;
}
