import { Select } from './components/Select.js';
import { useRoutedState } from './workspace-route.js';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, Plus, RefreshCw } from 'lucide-react';
import type { MarketResearchJob } from '../../../packages/contracts/market-research.js';
import { api, json } from './api.js';
import { statusToneClass } from './status-vocabulary.js';
import { InlineError } from './components/states.js';
import { Modal } from './components/Modal.js';

export const researchStateLabels:Record<string,string>={CREATED:'已创建',COLLECTING:'采集中',NORMALIZING:'标准化',IMPORTING:'导入',ANALYZING:'AI 分析',REVIEW_REQUIRED:'待人工审核',COMPLETED:'已完成',FAILED:'失败'};
type ModelOptions = { lightModels:string[]; currentLightModel:string };
const profileName=(value:string)=>value==='shampoo'?'洗发水':value==='facial_cleanser'?'洗面奶':value;
const modelFailure=(job:MarketResearchJob)=>job.failedStage==='ANALYZING'&&!!job.marketBatchId;
const quotaFailure=(job:MarketResearchJob)=>job.errorCode==='PROVIDER_QUOTA_EXHAUSTED'||/insufficient_quota/i.test(job.safeMessage??'');
export function MarketResearchPanel({onBatchReady,onChanged,onProject,selectedBatchId}:{onBatchReady:(id:string)=>void;onChanged:()=>void;onProject:(id:string)=>void;selectedBatchId?:string}){
  const [jobs,setJobs]=useState<MarketResearchJob[]>([]),[open,setOpen]=useRoutedState<boolean>('researchForm',false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [models,setModels]=useState<ModelOptions|null>(null),[retryModels,setRetryModels]=useState<Record<string,string>>({});
  const [collectionProfile,setCollectionProfile]=useState<'shampoo'|'facial_cleanser'>('shampoo');
  const [selectedJobId,setSelectedJobId]=useRoutedState<string|null>('researchJob',null),[historyOpen,setHistoryOpen]=useRoutedState<boolean>('researchHistory',false);
  const [historyFilter,setHistoryFilter]=useRoutedState<'ALL'|'RUNNING'|'COMPLETED'|'CREATED'>('researchFilter','ALL',['ALL','RUNNING','COMPLETED','CREATED']);
  const shownBatch=useRef('');

  const load=async()=>{const values=await api<MarketResearchJob[]>('/market-research-jobs');setJobs(values);const active=values.find(item=>item.marketBatchId&&item.state==='REVIEW_REQUIRED');if(!selectedBatchId&&active?.marketBatchId&&shownBatch.current!==active.marketBatchId){shownBatch.current=active.marketBatchId;onBatchReady(active.marketBatchId);}};
  useEffect(()=>{void load().catch(e=>setError((e as Error).message));void api<ModelOptions>('/market-research-models').then(setModels).catch(()=>{});const timer=setInterval(()=>void load().catch(()=>{}),2000);return()=>clearInterval(timer);},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError('');try{const created=await api<MarketResearchJob>('/market-research-jobs',json({sourcePlatform:'jd',collectionProfile,targetCount:Number(data.get('targetCount')),maxPages:Number(data.get('maxPages'))}));setSelectedJobId(created.id);setOpen(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function action(path:string,body:unknown={}){setBusy(true);setError('');try{await api(path,json(body));await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const featured=jobs.find(job=>job.id===selectedJobId)??jobs.find(job=>job.marketBatchId===selectedBatchId)??jobs.find(job=>job.state==='FAILED'||job.state==='REVIEW_REQUIRED'||job.state==='ANALYZING'||job.state==='COLLECTING')??jobs[0];
  const runs=featured&&Array.isArray(featured.manifestData.aiRuns)?featured.manifestData.aiRuns as Array<{model?:string;status?:string;fallbackReason?:string}>:[];
  const recoveredRun=[...runs].reverse().find(run=>run.status==='SUCCEEDED'&&run.fallbackReason);
  const failureReason=(job:MarketResearchJob)=>quotaFailure(job)?'当前模型额度或频率受限':job.errorCode==='REQUEST_INCOMPATIBLE'?'当前模型与输出格式不兼容':job.errorCode==='MODEL_NOT_CONFIGURED'?'上次选择的模型已不在当前能力配置中':'AI 分析尚未完成';
  return <section className="market-research-panel card"><div className="market-research-head"><div><h2>研究工作区</h2></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/>新建研究</button></div>
    {jobs.length>1&&<div className="research-selector"><label>当前研究<Select aria-label="选择市场研究" value={featured?.id??''} onChange={event=>{const job=jobs.find(item=>item.id===event.target.value);if(job){setSelectedJobId(job.id);if(job.marketBatchId)onBatchReady(job.marketBatchId);}}}>{jobs.map(job=><option key={job.id} value={job.id}>{profileName(job.collectionProfile)} · {new Date(job.createdAt).toLocaleDateString('zh-CN')} · {researchStateLabels[job.state]}</option>)}</Select></label><button className="text-button" onClick={()=>setHistoryOpen(true)}>研究历史<ArrowRight size={14}/></button></div>}
    {error&&<InlineError onRetry={()=>{setError('');void load().catch(e=>setError(e.message));}}>{error}</InlineError>}
    {featured?<article className={`market-research-feature ${featured.state==='FAILED'?'is-failed':''}`}><div className="market-research-feature-main"><span className={`badge ${statusToneClass(featured.state)}`}>{modelFailure(featured)&&featured.state==='FAILED'?'AI 分析待完成':researchStateLabels[featured.state]}</span><h3>京东联盟 · {profileName(featured.collectionProfile)}</h3><p>京粉精选商品池 · 已扫描 {featured.scannedCount} 条{!featured.marketBatchId&&` · 有效样本 ${featured.validCount} 条`}</p><small>{featured.initiatingProjectId?'由产品项目发起':'全局发起'} · {new Date(featured.createdAt).toLocaleDateString('zh-CN')}</small>{featured.state==='FAILED'&&<p className="market-research-failure">{modelFailure(featured)?`数据采集与导入已完成，${featured.validCount} 条样本已保存。${failureReason(featured)}；可只重试 AI 分析。`:featured.safeMessage}</p>}{recoveredRun&&featured.state==='REVIEW_REQUIRED'&&<details className="research-runtime-note"><summary>备用模型分析记录</summary><p className="muted">原模型未完成本次请求，已使用 {recoveredRun.model} 完成分析；机会仍需人工审核。</p></details>}</div><div className="market-research-feature-actions">{featured.state==='FAILED'&&modelFailure(featured)&&models&&models.lightModels.length>1&&<details className="market-model-choice"><summary>选择备用模型</summary><label>分析模型<Select aria-label="重试市场分析使用的模型" value={retryModels[featured.id]??''} onChange={event=>setRetryModels(value=>({...value,[featured.id]:event.target.value}))}><option value="">自动（推荐）</option>{models.lightModels.map(model=><option key={model} value={model}>{model}</option>)}</Select></label></details>}{featured.state==='FAILED'&&<button className="primary" disabled={busy} onClick={()=>action(`/market-research-jobs/${featured.id}/retry`,retryModels[featured.id]?{lightModelId:retryModels[featured.id]}:{})}><RefreshCw size={15}/>{modelFailure(featured)?'重试 AI 阶段':'从失败阶段继续'}</button>}{featured.marketBatchId&&<button onClick={()=>onBatchReady(featured.marketBatchId!)}>查看已保存样本<ArrowRight size={15}/></button>}{featured.state==='REVIEW_REQUIRED'&&<button disabled={busy} onClick={()=>action(`/market-research-jobs/${featured.id}/complete`)}>完成本次审核</button>}{featured.initiatingProjectId&&<button className="text-button" onClick={()=>onProject(featured.initiatingProjectId!)}>查看发起项目</button>}</div></article>:<p className="muted">暂无研究任务。</p>}
    {featured&&<ol className="research-stage-track" aria-label="研究任务进度">{(['CREATED','COLLECTING','NORMALIZING','IMPORTING','ANALYZING','REVIEW_REQUIRED','COMPLETED'] as const).map((stage,index)=>{const stages=['CREATED','COLLECTING','NORMALIZING','IMPORTING','ANALYZING','REVIEW_REQUIRED','COMPLETED'];const current=featured.state==='FAILED'?featured.failedStage:featured.state;return <li key={stage} className={stage===current?'current':index<stages.indexOf(current??'')?'done':''}><span>{index+1}</span><strong>{({CREATED:'创建任务',COLLECTING:'数据采集',NORMALIZING:'标准化',IMPORTING:'样本保存',ANALYZING:'AI 分析',REVIEW_REQUIRED:'人工审核',COMPLETED:'完成'} as Record<string,string>)[stage]}</strong></li>;})}</ol>}
    {featured&&<p className="research-current-description" role="status">{featured.state==='FAILED'?`${researchStateLabels[featured.failedStage??'FAILED']}暂未完成：${modelFailure(featured)?'样本已保存，请重试 AI 阶段。':'请查看错误原因，从失败阶段继续。'}`:({CREATED:'已创建，等待采集。',COLLECTING:'采集中，请等待结果。',NORMALIZING:'整理商品字段与有效样本。',IMPORTING:'保存样本与来源记录。',ANALYZING:'基于已保存样本分析机会。',REVIEW_REQUIRED:'请审核机会候选，通过后创建或关联项目。',COMPLETED:'审核完成，可查看结果与关联项目。'} as Record<string,string>)[featured.state]}</p>}
    {historyOpen&&<Modal title="全部市场研究" className="workspace-drawer" onClose={()=>setHistoryOpen(false)}><div className="market-research-history"><div className="workspace-reference-tabs" role="tablist" aria-label="研究状态">{([['ALL','全部'],['RUNNING','进行中'],['COMPLETED','已完成'],['CREATED','已创建']] as const).map(([key,label])=><button key={key} role="tab" aria-selected={historyFilter===key} className={historyFilter===key?'active':''} onClick={()=>setHistoryFilter(key)}>{label}</button>)}</div><div>{jobs.filter(job=>historyFilter==='ALL'||historyFilter==='RUNNING'?historyFilter==='ALL'||['COLLECTING','NORMALIZING','IMPORTING','ANALYZING'].includes(job.state):job.state===historyFilter).map(job=><article key={job.id}><span><strong>京东联盟 · {profileName(job.collectionProfile)}</strong><small>{researchStateLabels[job.state]} · 有效样本 {job.validCount} 条 · {new Date(job.createdAt).toLocaleDateString('zh-CN')}</small></span><button onClick={()=>{setSelectedJobId(job.id);setHistoryOpen(false);if(job.marketBatchId)onBatchReady(job.marketBatchId);}}>进入研究<ArrowRight size={14}/></button></article>)}</div></div></Modal>}
    {open&&<Modal title="新建市场研究" onClose={()=>setOpen(false)} compact><form className="market-research-form" onSubmit={create}><label>数据源<Select value="jd" disabled><option value="jd">京东联盟</option></Select></label><label>品类<Select value={collectionProfile} onChange={event=>setCollectionProfile(event.target.value as 'shampoo'|'facial_cleanser')}><option value="shampoo">洗发水</option><option value="facial_cleanser">洗面奶</option></Select></label><label>目标样本数<input name="targetCount" type="number" min="1" max="100" defaultValue="50"/></label><details><summary>高级采集范围</summary><label>最大分页<input name="maxPages" type="number" min="1" max="20" defaultValue="10"/></label></details><div className="market-research-form-actions"><button type="button" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={busy}>开始研究</button></div></form></Modal>}
  </section>;
}
