import { Select } from './components/Select.js';
import { presentWorkQueue, isFailedWork, compactActivity } from './work-queue-presentation.js';
import { Button } from './components/Button.js';
import { StatusTag } from './components/StatusTag.js';
import { deadlineNotice } from "../../../packages/contracts/deadline.js";
import { useRoutedState } from './workspace-route.js';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, BrainCircuit, Check, Clock3, ClipboardList, Plus, Sparkles } from 'lucide-react';
import type { WorkTarget } from '../../../packages/contracts/overview-work.js';
import type { ManualWorkInput, ManualWorkItem, QueueItem, WorkEntity, WorkSource } from '../../../packages/contracts/work-queue.js';
import { api, json } from './api.js';
import { WorkIcon,eventAppearance,eventTitle } from './components/work-appearance.js';
import { QueueGroups, workSourceLabels } from './components/queue-row.js';
import { Modal } from './components/Modal.js';
import { batchDisplayName, opportunityDisplayTitle } from './display-text.js';

export type WorkQueueResponse={attention:QueueItem[];running:import('../../../packages/contracts/overview-work.js').WorkItem[];updatedAt:string};
type Candidate={type:WorkEntity;id:string;label:string;target:WorkTarget};
type TaskDraft=ManualWorkInput & {requirements?:string[];workflow?:string;targetPage?:string|null};
type CopilotResult<T>={runId:string;model:string;cached:boolean;inputBytes:number;output:T};
type Advice={facts:Array<{text:string;sourceRef:string}>;inferences:Array<{text:string;sourceRefs:string[]}>;recommendations:Array<{workItemId:string;why:string;urgency:string;sourceRefs:string[]}>;projectHealth:Array<{projectId:string;assessment:string;risk:string;nextStep:string}>};
type Answer={facts:Array<{text:string;sourceRef:string}>;inferences:Array<{text:string;sourceRefs:string[]}>;answer?:string;completed?:string[];needsAttention?:string[];nextSteps?:string[];suggestedNextSteps?:string[];uncertainty:string};
const sourceLabel=workSourceLabels;
const entityLabel:Record<WorkEntity,string>={PROJECT:'产品项目',SKU:'商品 SKU',OPPORTUNITY:'市场机会',CONTENT_KIT:'内容方案',CONTENT_PAGE:'内容页'};
const deadlineLabel=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):null;
const urgencyLabel=(value:string)=>({high:'优先处理',medium:'按计划处理',low:'后续处理'} as Record<string,string>)[value.toLowerCase()]??'请核对优先级';
const localDate=(value:string|null)=>{if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const displayTitle=(item:QueueItem)=>item.kind==='opportunity'?opportunityDisplayTitle(item.title):item.title;
const displayContext=(item:QueueItem)=>item.kind==='opportunity'?batchDisplayName(item.context):item.context;

export function WorkQueueView({queue,onWork,onRefresh,recentEvents}:{queue:WorkQueueResponse;onWork:(target:WorkTarget)=>void;onRefresh:()=>Promise<void>;recentEvents:Array<{id:string;project_id:string;project_name:string;note:string;event_type?:string;created_at:string}>}){
  const [modal,setModal]=useRoutedState<'create'|'detail'|'queue'|'activity'|null>('queueDrawer',null,['create','detail','queue','activity']),[selected,setSelected]=useState<QueueItem|null>(null),[targets,setTargets]=useState<Candidate[]>([]);
  const [draft,setDraft]=useState<TaskDraft|null>(null),[naturalText,setNaturalText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [filter,setFilter]=useState<'ALL'|WorkSource>('ALL'),[advice,setAdvice]=useState<CopilotResult<Advice>|null>(null),[answer,setAnswer]=useState<CopilotResult<Answer>|null>(null),[question,setQuestion]=useState('');
  const [aiBusy,setAiBusy]=useState(false);
  const ordered=presentWorkQueue(queue.attention);
  const filtered=filter==='ALL'?ordered:ordered.filter(item=>item.source===filter);
  const urgent=ordered.find(item=>isFailedWork(item)||item.source==='MANAGER_ASSIGNED');
  const activities=compactActivity(recentEvents);
  useEffect(()=>{if(modal==='create')api<Candidate[]>('/work-queue/targets').then(setTargets).catch(e=>setError(e.message));},[modal]);
  const [queueItemId,setQueueItemId]=useRoutedState<string|null>('queueItem',null);
  useEffect(()=>{if(queueItemId){const item=queue.attention.find(item=>item.id===queueItemId);if(item)setSelected(item);}},[queueItemId,queue]);
  function open(item:QueueItem){if(item.manualTaskId){setSelected(item);setQueueItemId(item.id);setModal('detail');setError('');}else onWork(item.target);}
  async function updateStatus(status:ManualWorkItem['status']){if(!selected?.manualTaskId)return;setBusy(true);setError('');try{await api(`/work-queue/manual/${selected.manualTaskId}`,json({status},'PATCH'));await onRefresh();setModal(null);}catch(e){setError(e instanceof Error?e.message:'任务更新失败');}finally{setBusy(false);}}
  async function structure(){if(!naturalText.trim())return;setBusy(true);setError('');try{const result=await api<{draft:TaskDraft}>('/system-copilot/structure-task',json({text:naturalText.trim()}));setDraft(result.draft);}catch(e){setError(e instanceof Error?e.message:'任务整理失败');}finally{setBusy(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget),selectedTarget=String(data.get('relatedEntity')).split(':');
    if(selectedTarget.length!==2){setError('请选择真实关联对象');return;}
    const dateValue=String(data.get('deadline')||'');const deadline=dateValue?new Date(dateValue).toISOString():null;
    const input:ManualWorkInput={title:String(data.get('title')||'').trim(),source:String(data.get('source')) as ManualWorkInput['source'],priority:String(data.get('priority')) as ManualWorkInput['priority'],deadline,objective:String(data.get('objective')||'').trim(),acceptanceCriteria:String(data.get('acceptanceCriteria')||'').split('\n').map(line=>line.trim()).filter(Boolean),relatedEntityType:selectedTarget[0] as WorkEntity,relatedEntityId:selectedTarget[1]!};
    setBusy(true);setError('');try{await api('/work-queue/manual',{...json(input),headers:{'Idempotency-Key':crypto.randomUUID()}});await onRefresh();setModal(null);setDraft(null);setNaturalText('');}catch(e){setError(e instanceof Error?e.message:'任务保存失败');}finally{setBusy(false);}}
  async function recommend(){setAiBusy(true);setError('');try{setAdvice(await api<CopilotResult<Advice>>('/system-copilot/recommend',json({})));}catch(e){setError(e instanceof Error?e.message:'建议生成失败');}finally{setAiBusy(false);}}
  async function ask(mode:'ask'|'day'|'week'){setAiBusy(true);setError('');try{setAnswer(await api<CopilotResult<Answer>>(mode==='ask'?'/system-copilot/ask':'/system-copilot/summary',json(mode==='ask'?{question:question.trim()}:{period:mode})));}catch(e){setError(e instanceof Error?e.message:'分析未完成');}finally{setAiBusy(false);}}
  const displayItems=ordered;
  return <div className="work-queue-ui">
    
    {error&&<p className="notice-error" role="alert">{error}</p>}
    <section className="queue-priority card" aria-label="优先处理"><div><small>{urgent?'优先处理':'工作安排'}</small><h2>{urgent?displayTitle(urgent):'没有紧急事项'}</h2><p>{urgent?urgent.reason:'从待办中选择下一件事。'}</p>{urgent&&<div className="queue-priority-meta"><StatusTag domain="queue" status={urgent.status}/>{urgent.source==='MANAGER_ASSIGNED'&&<span>领导指派</span>}{urgent.deadline&&<time dateTime={urgent.deadline}>截止 {deadlineLabel(urgent.deadline)}</time>}{urgent.deadline&&deadlineNotice(urgent.deadline,urgent.status)&&<span className="queue-overdue">{deadlineNotice(urgent.deadline,urgent.status)}</span>}</div>}</div><Button variant="primary" onClick={()=>urgent?open(urgent):displayItems[0]?open(displayItems[0]):setModal('create')}>{urgent?(urgent.manualTaskId?'查看任务':urgent.action):displayItems[0]?'查看下一项':'新建任务'}<ArrowRight size={16}/></Button></section>
    <div className="work-queue-main batch1-queue-layout"><section className="work-queue-list card"><header><h3>其他待处理事项</h3><button onClick={()=>setModal('queue')}>查看全部任务<ArrowRight size={15}/></button></header>
      <div className="reference-queue-rows"><QueueGroups items={displayItems.filter(item=>item.id!==urgent?.id)} limit={5} onOpen={open}/>{!displayItems.filter(item=>item.id!==urgent?.id).length&&<p className="muted">没有其他待处理事项。</p>}</div></section>
      <aside className="work-queue-aside"><details className="card work-queue-advice"><summary>AI 今日建议</summary>{!advice&&<p className="muted small">按当前待办生成优先处理建议。</p>}<button disabled={aiBusy||!queue.attention.length} onClick={()=>void recommend()}><Sparkles size={15}/>{aiBusy?'正在分析':'分析当前待办'}</button>{advice&&<div className="work-queue-ai-result"><small>AI 判断 · 基于当前工作队列</small>{advice.output.recommendations.map((item,index)=>{const target=queue.attention.find(work=>work.id===item.workItemId);return <article key={`${item.workItemId}-${index}`}><strong>{index+1}. {target?displayTitle(target):'任务已变化'}</strong><p>{item.why}</p><small>{urgencyLabel(item.urgency)}</small>{target&&<button onClick={()=>open(target)}>进入任务<ArrowRight size={13}/></button>}</article>;})}<details><summary>系统事实、AI 判断与项目健康</summary><small>模型：{advice.model} · 摘要输入 {advice.inputBytes} 字节{advice.cached?' · 本次复用已有结果':''}</small><strong>系统事实</strong>{advice.output.facts.map((item,index)=><p key={index}>{item.text} <small>{item.sourceRef}</small></p>)}<strong>AI 判断</strong>{advice.output.inferences.map((item,index)=><p key={index}>{item.text}</p>)}{advice.output.projectHealth.map(item=><p key={item.projectId}>{item.assessment} · {item.nextStep}</p>)}</details></div>}</details>
      <details className="card work-queue-ask"><summary>提问或生成工作摘要</summary><label>向系统提问<input value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} placeholder="例如：LEADR 当前还有哪些阻塞？"/></label><div><button disabled={aiBusy||question.trim().length<2} onClick={()=>void ask('ask')}>提问</button><button disabled={aiBusy} onClick={()=>void ask('day')}>今日摘要</button><button disabled={aiBusy} onClick={()=>void ask('week')}>本周摘要</button></div>{answer&&<div className="work-queue-ai-result"><small>系统事实与 AI 判断分开呈现 · 输入 {answer.inputBytes} 字节</small>{answer.output.answer&&<p>{answer.output.answer}</p>}{answer.output.facts.map((item,index)=><p key={index}>【系统事实】{item.text}</p>)}{answer.output.inferences.map((item,index)=><p key={index}>【AI 判断】{item.text}</p>)}{answer.output.completed?.map((item,index)=><p key={`c${index}`}>已记录：{item}</p>)}{answer.output.needsAttention?.map((item,index)=><p key={`n${index}`}>待处理：{item}</p>)}{(answer.output.nextSteps??answer.output.suggestedNextSteps??[]).map((item,index)=><p key={`s${index}`}>【建议下一步】{item}</p>)}<small>{answer.output.uncertainty}</small></div>}</details>
      <section className="card work-queue-activity"><header><h3>最近动态</h3><button className="text-button" onClick={()=>setModal('activity')}>查看全部<ArrowRight size={15}/></button></header>{recentEvents.length ? <div className="work-queue-activity-list">{activities.slice(0,4).map(event=><button key={event.id} type="button" onClick={()=>onWork({view:'projects',projectId:event.project_id})}><WorkIcon appearance={eventAppearance(event.event_type??'')}/><span className="activity-summary-copy"><strong title={event.project_name}>{eventTitle(event.event_type??'',event.note)}{event.count>1?` ×${event.count}`:''}</strong><small title={event.note}>{event.note}</small></span><time dateTime={event.created_at}>{new Date(event.created_at).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></button>)}</div> : <p className="muted">暂无业务动态。</p>}</section>
      </aside>
    </div>

    {modal==='activity'&&<Modal title="最近业务动态" onClose={()=>setModal(null)}><div className="work-queue-activity-list">{recentEvents.map(event=><button key={event.id} onClick={()=>onWork({view:'projects',projectId:event.project_id})}><WorkIcon appearance={eventAppearance(event.event_type??'')}/><span><strong>{event.project_name}</strong><small>{event.note}</small></span><time dateTime={event.created_at}>{new Date(event.created_at).toLocaleString('zh-CN')}</time></button>)}</div></Modal>}
    {modal==='queue'&&<Modal title={`工作队列 · ${queue.attention.length} 项`} onClose={()=>setModal(null)}><div className="work-queue-dialog"><div className="work-queue-filters" role="group" aria-label="按任务来源筛选">{(['ALL','MANAGER_ASSIGNED','SELF_CREATED','SYSTEM_GENERATED','AI_RECOMMENDED'] as const).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value==='ALL'?'全部':sourceLabel[value]} <small>{value==='ALL'?ordered.length:ordered.filter(item=>item.source===value).length}</small></button>)}</div><div className="work-queue-rows"><QueueGroups items={filtered} onOpen={item=>{setModal(null);open(item);}}/>{!filtered.length&&<p className="muted">当前筛选下没有任务。</p>}</div></div></Modal>}
    {modal==='create'&&<Modal title="新建工作任务" onClose={()=>setModal(null)}><div className="work-queue-create"><div className="work-queue-natural"><label>领导指派原话（可选）<textarea rows={3} value={naturalText} onChange={e=>setNaturalText(e.target.value)} placeholder="明天前完成 LEADR F01 首图优化，突出香氛和蓬松，输出 3 版。"/></label><button type="button" disabled={busy||naturalText.trim().length<4} onClick={()=>void structure()}>{busy?'正在整理':'AI 整理成任务草稿'}</button><small>模型只整理文字并选择现有对象；下面的正式任务须由你核对后保存。</small></div>{error&&<p className="notice-error" role="alert">{error}</p>}<form key={draft?.relatedEntityId??'manual'} className="work-queue-form" onSubmit={e=>void create(e)}><label>任务标题<input name="title" required maxLength={160} defaultValue={draft?.title??''}/></label><label>来源<Select name="source" defaultValue="MANAGER_ASSIGNED"><option value="MANAGER_ASSIGNED">领导指派</option><option value="SELF_CREATED">自建任务</option></Select></label><label>优先级<Select name="priority" defaultValue={draft?.priority??'NORMAL'}><option value="NORMAL">普通</option><option value="HIGH">高</option><option value="URGENT">紧急</option><option value="LOW">低</option></Select></label><label>截止时间<input name="deadline" type="datetime-local" defaultValue={localDate(draft?.deadline??null)}/></label><label className="wide">关联业务对象<Select name="relatedEntity" required defaultValue={draft?`${draft.relatedEntityType}:${draft.relatedEntityId}`:''}><option value="">请选择项目、SKU、机会或内容页</option>{targets.map(item=><option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.label} · {entityLabel[item.type]}</option>)}</Select></label><label className="wide">任务目标<textarea name="objective" required rows={2} defaultValue={draft?.objective??''}/></label><label className="wide">验收标准（每行一项）<textarea name="acceptanceCriteria" required rows={3} defaultValue={draft?.acceptanceCriteria.join('\n')??''}/></label>{draft&&<p className="wide muted">AI 草稿{draft.targetPage?` · ${draft.targetPage}`:''}{draft.requirements?.length?`：${draft.requirements.join('、')}`:''}。请确认目标和验收标准。</p>}<div className="wide work-queue-form-actions"><button type="button" onClick={()=>setModal(null)}>取消</button><button className="primary" disabled={busy}>{busy?'正在保存':'确认并创建任务'}</button></div></form></div></Modal>}
    {modal==='detail'&&selected&&<Modal title={selected.title} onClose={()=>setModal(null)} compact><div className="work-queue-detail"><p><strong>来源：</strong>{sourceLabel[selected.source]}　<strong>状态：</strong>{selected.status}</p><p><strong>任务目标：</strong>{selected.context}</p><p><strong>验收标准：</strong>{selected.reason}</p><p><strong>排序依据：</strong>{selected.rankingReasons.join(' · ')}</p>{selected.deadline&&<p><strong>截止：</strong>{deadlineLabel(selected.deadline)}</p>}{error&&<p className="notice-error" role="alert">{error}</p>}<div className="work-queue-form-actions"><button onClick={()=>{setModal(null);onWork(selected.target);}}>进入工作位置<ArrowRight size={15}/></button><button disabled={busy} onClick={()=>void updateStatus('IN_PROGRESS')}>标记进行中</button><button className="primary" disabled={busy} onClick={()=>void updateStatus('COMPLETED')}><Check size={15}/>确认完成</button></div></div></Modal>}
  </div>;
}
